### ISSUE TITLE
Grauenhafte Übersetzung

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs.de-de#1]
@hb9tws commented on [Mon Mar 26 2018](https://github.com/MicrosoftDocs/xamarin-docs/issues/90)

Die deutsche Übersetzung ist einfach grauenhaft.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: 969ae3fb-fa08-217b-a62f-105317ea811a
* Version Independent ID: 49deb3eb-6726-62d1-1684-6816d4b4b1cb
* Content: [HttpClient-Stapel und Implementierung von SSL/TLS-Selektor für Android - Xamarin](https://docs.microsoft.com/de-ch/xamarin/android/app-fundamentals/http-stack?tabs=vswin#feedback)
* Content Source: [docs/android/app-fundamentals/http-stack.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/android/app-fundamentals/http-stack.md)
* Service: **unspecified**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

---

@MagicAndre1981 commented on [Fri Apr 06 2018](https://github.com/MicrosoftDocs/xamarin-docs/issues/90#issuecomment-379254776)

always use an English Visual Studio and read en-us resources. translated error messages and documentation are always a pain. 

---

@conceptdev commented on [Mon Apr 16 2018](https://github.com/MicrosoftDocs/xamarin-docs/issues/90#issuecomment-381770119)

Thanks for the feedback @MagicAndre1981.

---

@Sara-Nicolini commented on [Tue Apr 24 2018](https://github.com/MicrosoftDocs/xamarin-docs/issues/90#issuecomment-384107663)

@MagicAndre1981, thanks for your feedback. The page in question was machine-translated which we understand it is not always ideal and fully understandable. We have recently added a toggle "Auf Englisch lesenon" on the right nav of the topic that allows you to switch to the English version of the topic without having to change the language settings.

**Comment by CeciAc** [comment]
As per @Sara-Nicolini 's comment, there´s no further action for this issue since the content is MT and the new toggle "Auf Englisch lesenon" will switch to the English version when needed.

Kind regards,
Microsoft DOCS International Team

**Comment by MagicAndre1981** [comment]
If I login with my Microsoft account can this setting be stored in my Microsoft account to have the toogle position set on all devices I use?

**Comment by CeciAc** [comment]
Hi @MagicAndre1981 
This issue is closed since is out of the scope of the Localization team
Adding @nokura  to help you on your concern regarding the site features.

Kind regards,
Microsoft DOCS International Team
