### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by AlexSchuetz** [MicrosoftDocs/xamarin-docs.de-de#11]
The method `void Connectivity_ConnectivityChanged(ConnectivityChangedEventArgs  e)` needs the additional first argument `object sender` to be able to be added as `EventHandler`.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 33758e0e-bd5d-0829-b458-6cdfabe98b44
* Version Independent ID: d3ed3057-798b-44b9-b5a0-35e657f7a4b8
* Content: [Xamarin.Essentials: Konnektivität - Xamarin](https://docs.microsoft.com/de-de/xamarin/essentials/connectivity?tabs=ios)
* Content Source: [docs/essentials/connectivity.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/essentials/connectivity.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
put in a PR: https://github.com/MicrosoftDocs/xamarin-docs/pull/784

**Comment by LisandroSu** [comment]
Hello @AlexSchuetz 

Thanks for the feedback!

I'll be closing this issue as it was fix in the PR above.

Kind Regards,
Microsoft DOCS International Team
