### ISSUE TITLE
"File Not Found"

### ISSUE THREAD

**Issue by EdwardCaulfield** [MicrosoftDocs/xamarin-docs.de-de#20]
Attempting to install on Mac OS Mojave and even though I can set the path as documented in this guide, it still shows a "Not Found" error for the SDK location.  I am not at all successful in the NDK location and even though I am able to navigate to the Java SDK (JDK) Location and it gets a green "Found" - once I click on "OK" and return to the dialog, all fields are empty again.

I am using the version 7.7 (build 1868) of Visual Studio for Mac (Community edition).

Much appreciate your help clarifying this situation.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Microsoft Mobile OpenJDK-Verteilung (Vorschauversion) - Xamarin](https://docs.microsoft.com/de-de/xamarin/android/get-started/installation/openjdk)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

**Comment by vyedin** [comment]
@EdwardCaulfield would you mind filing this in VS Mac Report an Issue so we track it in our bug system? Please also attach your VS for Mac logs.

**Comment by EdwardCaulfield** [comment]
Will do.

**Comment by CeciAc** [comment]
Hi @vyedin @EdwardCaulfield 
Should I move this issue to the en-us repository?
Please advise,

Kind regards

**Comment by EdwardCaulfield** [comment]
Yes, please.

Kind Regards,

Edward

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #1213](https://github.com/MicrosoftDocs/xamarin-docs/issues/1213) via [**ZenHub**](https://www.zenhub.com/)
