### ISSUE TITLE
Fehler in TranslateButton.Click Code

### ISSUE THREAD

**Issue by pantalooon** [MicrosoftDocs/xamarin-docs.de-de#24]
translatedNumber = PhonewordTranslator.ToNumber(phoneNumberText.Text);

müsste

translatedNumber = Core.PhonewordTranslator.ToNumber(phoneNumberText.Text);

lauten

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 672a11c0-fb8f-4b75-f42c-23429f52c35a
* Version Independent ID: 51f9c1e4-fa5d-b6ac-6081-c4c3189191f7
* Content: [Schnellstart für „Hallo, Android“-Multiscreen - Xamarin](https://docs.microsoft.com/de-de/xamarin/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart?pivots=windows)
* Content Source: [docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #1274](https://github.com/MicrosoftDocs/xamarin-docs/issues/1274) via [**ZenHub**](https://www.zenhub.com/)
