### ISSUE TITLE
l

### ISSUE THREAD

**Issue by TheFatTurtle** [MicrosoftDocs/xamarin-docs.de-de#25]
l

---
#### Dokumentdetails
⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c00880be-094d-7f7d-093a-46d3b25dec93
* Version Independent ID: 1ea1c05f-262a-b654-78ee-ca54b245bd48
* Content: [Verwenden der Modellklasse - Xamarin](https://docs.microsoft.com/de-de/xamarin/graphics-games/monogame/3d/part1)
* Content Source: [docs/graphics-games/monogame/3d/part1.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/graphics-games/monogame/3d/part1.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
The feedback is empty.
Closing and locking conversation.

Kind regards
