### ISSUE TITLE
k

### ISSUE THREAD

**Issue by ZollZZ** [MicrosoftDocs/xamarin-docs.de-de#26]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 95e14db5-474b-af2f-7d90-7fd0f029a137
* Version Independent ID: 5d2be08c-1513-a44f-93af-b655f5349c53
* Content: [Senden von Pushbenachrichtigungen - Xamarin](https://docs.microsoft.com/de-de/xamarin/xamarin-forms/data-cloud/push-notifications/)
* Content Source: [docs/xamarin-forms/data-cloud/push-notifications/index.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/xamarin-forms/data-cloud/push-notifications/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by LisandroSu** [comment]
Hallo, @ZollZZ ,

Wir freuen uns über Ihren Kommentar und bemühen uns, Ihre Erfahrungen mit docs.microsoft.com zu verbessern. Wir benötigen jedoch weitere Informationen, um auf Ihr Feedback eingehen zu können. Können Sie uns bitte nähere Informationen geben und Ihren Kommentar erläutern?

Mit freundlichen Grüßen
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hallo, @ZollZZ 

Nochmals vielen Dank für Ihren Kommentar.
Leider fehlen uns immer noch Informationen und wir können Ihr Feedback nicht bearbeiten. Wir schließen dieses GitHub-Problem jetzt, möchten Sie aber ermutigen, in Zukunft weiteres Feedback zu geben.

Mit freundlichen Grüßen
Microsoft DOCS International Team
