### ISSUE TITLE
Sehr gut strukturierte Einführung

### ISSUE THREAD

**Issue by minigigs** [MicrosoftDocs/xamarin-docs.de-de#37]
Wunderbar, wenn man ohne großartige Vorkenntnisse erst einmal die ersten Schritte machen möchte, um zu prüfen, ob alle Komponenten, die man zur Entwicklung und zum Testen von Android Apps braucht, auch laufen.
Etwas mehr als nur ein "Hello World".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: Schnellstart - Xamarin](https://docs.microsoft.com/de-de/xamarin/android/get-started/hello-android/hello-android-quickstart?pivots=windows)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by srvbpigh** [comment]
Hello, @minigigs
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @minigigs

vielen Dank für Ihr Feedback. Es freut uns, dass Sie mir unserer Dokumentation zufrieden sind. 
Sie können gerne weiterhin Feedback abgeben, damit wir die Servicequalität kontinuierlich verbessern können. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
