### ISSUE TITLE
Failed to generate SSH keys

### ISSUE THREAD

**Issue by Benny56** [MicrosoftDocs/xamarin-docs.de-de#39]
I followed the instructions and I could successfully connect to a virtual Mac. I could use the Mac  a couple of times as a build host, but after updating macOS all further connection attempts failed. Finally I setup a new VM with the latest macOS Catalina 10.15.4 and latest Xcode 11.4. I didn't install Visual Studio for Mac so far. SSH connection is working. The directory '%LOCALAPPDATA%\Xamarin\MonoTouch' on the windows machine is empty. 

The very first attempt to connect to the Mac failed with
```
'Failed to generate SSH keys. Make sure the environment is configured correctly. Details: cat: /Users/<user>/Library/Caches/Xamarin/XMA/Keys/0b087572-9fa0-41fe-985a-f9a7cbb4c1ca: No such file or directory
```

And indeed the directory '*/Xamarin...' didn't exist since Visual Studio for Mac wasn't installed. I expected that installing VS will be optional because of the hint:

```
If you would prefer not to install Visual Studio for Mac, Visual Studio 2019 can automatically...
```

I installed the latest VS for Mac now and cleared the directory '%LOCALAPPDATA%\Xamarin\MonoTouch' on the Windows machine to prevent the error

```
Unexpected error checking the SSH configuration of the "<mac name>" host.
An item with the same key has already been added.
```

The next attempt to connect failed with
```
'Failed to generate SSH keys. Make sure the environment is configured correctly. Details: cat: /Users/<user>/Library/Caches/Xamarin/XMA/Keys/1daf88d3-3572-4c88-97fc-fdab436111d7: No such file or directory
```

I verified that the key didn't exist, but other keys from previous attempts.

How to workaround?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 98c96bcc-1743-8d9f-f1b2-3c30d5b2a6e2
* Version Independent ID: f57a6157-332a-3f31-c785-7efa99e62711
* Content: [Durchführen einer Kopplung mit einem Mac für die Xamarin.iOS-Entwicklung - Xamarin](https://docs.microsoft.com/de-de/xamarin/ios/get-started/installation/windows/connecting-to-mac/)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/index.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/index.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by srvbpigh** [comment]
Hello, @Benny56
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @Benny56 , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
