### ISSUE TITLE
Manifest information missing

### ISSUE THREAD

**Issue by tsafadi** [MicrosoftDocs/xamarin-docs.de-de#40]
It would be good to know in what way you need to modify the Android manifest. For example you can add the permission:
&lt;uses-permission android:name="android.permission.CALL_PHONE" /&gt;
Or if you want to make it an optional feature:
&lt;uses-feature android:name="android.hardware.telephony" android:required="false"/&gt;

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9f4d0869-b5c2-c17b-63d4-f325856d1a79
* Version Independent ID: a5f487c3-4e56-838f-89a9-b8fa0dc13261
* Content: [Xamarin.Essentials: Wählhilfe - Xamarin](https://docs.microsoft.com/de-de/xamarin/essentials/phone-dialer#feedback)
* Content Source: [docs/essentials/phone-dialer.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/essentials/phone-dialer.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by srvbpigh** [comment]
Hello, @tsafadi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by jamesmontemagno** [comment]
This API doesn't require any permissions. It just launches the the dialer on the device or app that can be a dialer. You would only require that permission if you were making the call from your app.

**Comment by CeciAc** [comment]
Hello, @tsafadi 
Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations. 
We encourage you to provide your valuable feedback so that we can continue improve your experience. 

Kind regards,
