### ISSUE TITLE
Grammatik

### ISSUE THREAD

**Issue by meierdesigns** [MicrosoftDocs/xamarin-docs.de-de#44]
Ein- Clicked Ereignishandler erfordert den- async Modifizierer nur, wenn der Text des Handlers verwendet await .

[Hier Feedback eingeben]
Falsche Grammatik.

Ein- Clicked Ereignishandler erfordert den- async Modifizierer nur, wenn der Text des Handlers await verwendet.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 639e2203-e49e-5673-e2d5-bd2257411656
* Version Independent ID: 43735d55-f808-13bf-7e3b-8e7afbaa4616
* Content: [Xamarin.FormsGedrückt - Xamarin](https://docs.microsoft.com/de-de/xamarin/xamarin-forms/user-interface/button)
* Content Source: [docs/xamarin-forms/user-interface/button.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/xamarin-forms/user-interface/button.md)
* Product: ****
* Technology: ****
* GitHub Login: @olprod
* Microsoft Alias: ****

**Comment by srvbpigh** [comment]
Hello, @meierdesigns
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo @meierdesigns 

Vielen Dank für Ihren Beitrag.

Beiträge zu Übersetzungsproblemen in maschinell übersetzten Inhalten werden zurzeit nicht akzeptiert.

Wir schätzen Ihr Feedback und Ihre Vorschläge zu von Menschen übersetzten Inhalten. Diese werden verwendet, um die Engines für maschinelle Übersetzung zu trainieren. Mit der Zeit verbessern Ihre Beiträge also die Qualität menschlicher und maschineller Übersetzungen.

Anhand des ms.translationtype-Metadatenwerts im Header einer Inhaltsdatei können Sie zwischen menschlicher und maschineller Übersetzung unterscheiden. Dabei steht „HT“ für menschliche Übersetzung und „MT“ für maschinelle Übersetzung.

Vielen Dank für Ihre Unterstützung!

Microsoft DOCS Global Experience Team
