### ISSUE TITLE
Formatting of the Xamarin.Essentials start page differs from the en-us page

### ISSUE THREAD

**Issue by vividos** [MicrosoftDocs/xamarin-docs.de-de#46]
It seems the formatting of the de-de version of the article is off; headings are displayed as normal, while normal text is displayed as headings. The effect isn't seen on the en-use page.

--
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c420b152-7303-918a-dbc8-8d1e539c64ec
* Version Independent ID: fe85e24f-c3fc-3763-b1db-6b360fb08067
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/de-de/xamarin/essentials/)
* Content Source: [docs/essentials/index.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/essentials/index.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by vividos** [comment]
This seems to be fixed already. Can it be closed?

**Comment by jamesmontemagno** [comment]
@davidbritch
