### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by mikolaisebastian** [MicrosoftDocs/xamarin-docs.de-de#6]
I can't get an redeem code for TestFlight https://fastring.xamarinliveplayer.com/

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 79320e9a-8b52-1c24-0a5b-a7ef6a32b519
* Version Independent ID: 88548723-6f1b-50c1-163c-a9e151b024e8
* Content: [Xamarin Player Live-Setup - Xamarin](https://docs.microsoft.com/de-de/xamarin/tools/live-player/install?tabs=ios%2Cmacos)
* Content Source: [docs/tools/live-player/install.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/tools/live-player/install.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by gosali** [comment]
Hello, @mikolaisebastian , 

  

Thank you for your feedback. 

  

We are actively reviewing your comments and will get back to you soon. 

 

Kind regards, 

Microsoft DOCS International Team

**Comment by mikolaisebastian** [comment]
Now it works, thanks.
